wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.2
    start_time: 1632548617
    t:
      1:
      - 2
      - 3
      - 5
      4: 3.9.2
      5: 0.12.1
      8:
      - 1
      - 3
      - 5
architecture:
  desc: null
  value: NN
batch_size:
  desc: null
  value: 32
dataset:
  desc: null
  value: MNIST
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.001
loss_function:
  desc: null
  value:
    OUT_PDown: categorical_crossentropy
    OUT_PLeft: categorical_crossentropy
    OUT_PRight: categorical_crossentropy
    OUT_PUp: categorical_crossentropy
    OUT_Stp: binary_crossentropy
    OUT_bpm: mse
loss_weights:
  desc: null
  value:
    OUT_PDown: 1
    OUT_PLeft: 1
    OUT_PRight: 1
    OUT_PUp: 1
    OUT_Stp: 1
    OUT_bpm: 1
